# Generated by Django 5.0.6 on 2024-07-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_fooditem_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='updated_at',
        ),
    ]
