# Generated by Django 5.0.6 on 2024-07-09 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_fooditem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
